function slxPath = build_rover_dual_control_model()
%BUILD_ROVER_DUAL_CONTROL_MODEL Create the dual sim + real rover model.
%
% Stage 4: teleop -> /cmd_vel (real rover) + MCL MAP pose -> Set_RoverTwin
% (Unreal twin via maps/unreal_alignment.mat).

dualMatlab = fileparts(mfilename("fullpath"));
paths = rover_dual_setup_paths(dualMatlab);
modelName = "rover_dual_control";
modelNameChar = char(modelName);
modelDir = fullfile(paths.dualRoot, "simulink");
slxPath = fullfile(modelDir, modelName + ".slx");

if ~isfolder(modelDir)
    mkdir(modelDir);
end

setup_ros_humble();
spawn = rover_spawn_pose();
cfg = rover_cmd_vel_config();
unrealProject = rover_unreal_project_alias();
spawnPosStr = mat2str(spawn.sim_m, 8);
cameraPosStr = dual_align_camera_translation(paths.projectRoot, spawn);

load_system("simulink");
load_system("drivingsim3d");
load_system("sim3dlib");
load_system("roslib");

if bdIsLoaded(modelNameChar)
    close_system(modelNameChar, 0);
end

if isfile(slxPath)
    delete(slxPath);
end

new_system(modelNameChar);
open_system(modelNameChar);

configureModel(modelNameChar);
addTeleop(modelNameChar);
addMapPosePath(modelNameChar);
addUnreal(modelNameChar, unrealProject, spawn, spawnPosStr, cameraPosStr);
addRosPublisher(modelNameChar);
wireDualOutputs(modelNameChar);
addNotes(modelNameChar);

set_param(modelNameChar, "SimulationCommand", "update");
configureRuntimeCallbacks(modelNameChar);
save_system(modelNameChar, slxPath);
set_param(modelNameChar, "ZoomFactor", "FitSystem");

fprintf("Created dual Simulink model: %s\n", slxPath);
end

function configureModel(modelName)
set_param(modelName, ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "0.1", ...
    "StopTime", "inf", ...
    "SimulationMode", "normal");
end

function configureRuntimeCallbacks(modelName)
pathBootstrap = [ ...
    'dualRoot = fileparts(fileparts(get_param(bdroot, ''FileName''))); ' ...
    'addpath(fullfile(dualRoot, ''matlab'')); ' ...
    'addpath(fullfile(fileparts(dualRoot), ''matlab'')); ' ...
    'addpath(fullfile(fileparts(dualRoot), ''roversim'', ''MATLAB'')); ' ...
    ];

set_param(modelName, ...
    "InitFcn", [pathBootstrap 'rover_dual_init();'], ...
    "StartFcn", [pathBootstrap 'rover_dual_start();'], ...
    "StopFcn", [pathBootstrap 'rover_dual_stop();']);
end

function addTeleop(modelName)
interpFcnBlock = sprintf("simulink/User-Defined\nFunctions/Interpreted MATLAB\nFunction");

add_block("simulink/Sources/Clock", modelName + "/Teleop_Tick", ...
    "Position", [40 110 70 140]);

add_block(interpFcnBlock, modelName + "/Teleop_Linear", ...
    "MATLABFcn", "simulink_teleop_lin(u)", ...
    "Position", [115 90 245 120]);
add_block(interpFcnBlock, modelName + "/Teleop_Angular", ...
    "MATLABFcn", "simulink_teleop_ang(u)", ...
    "Position", [115 145 245 175]);

add_line(modelName, "Teleop_Tick/1", "Teleop_Linear/1", "autorouting", "on");
add_line(modelName, "Teleop_Tick/1", "Teleop_Angular/1", "autorouting", "on");

add_block("simulink/Sinks/Scope", modelName + "/Scope_Cmd_Linear", ...
    "Position", [285 90 315 120]);
add_block("simulink/Sinks/Scope", modelName + "/Scope_Cmd_Angular", ...
    "Position", [285 145 315 175]);
add_line(modelName, "Teleop_Linear/1", "Scope_Cmd_Linear/1", "autorouting", "on");
add_line(modelName, "Teleop_Angular/1", "Scope_Cmd_Angular/1", "autorouting", "on");
end

function addMapPosePath(modelName)
interpFcnBlock = sprintf('simulink/User-Defined\nFunctions/Interpreted MATLAB\nFunction');

add_block(interpFcnBlock, [modelName '/Mcl_Map_Pose'], ...
    'MATLABFcn', 'simulink_mcl_map_pose(u)', ...
    'OutputDimensions', '4', ...
    'Position', [240 280 420 340]);
add_block(interpFcnBlock, [modelName '/MapPose_To_Unreal'], ...
    'MATLABFcn', 'simulink_map_pose_to_unreal(u)', ...
    'OutputDimensions', '4', ...
    'Position', [480 300 640 360]);
add_block(interpFcnBlock, [modelName '/Unreal_Pose_Gate'], ...
    'MATLABFcn', 'simulink_unreal_pose_gate(u)', ...
    'OutputDimensions', '4', ...
    'Position', [680 300 840 360]);

set_param(modelName, 'SimulationCommand', 'update');

add_block('simulink/Signal Routing/Demux', [modelName '/Unreal_Pose_Demux'], ...
    'Outputs', '4', ...
    'Position', [890 305 895 355]);

add_block('simulink/Sinks/Scope', [modelName '/Scope_Map_Valid'], ...
    'Position', [420 230 450 260]);
add_block('simulink/Sinks/Scope', [modelName '/Scope_Unreal_Raw_X'], ...
    'Position', [660 230 690 260]);
add_block('simulink/Sinks/Scope', [modelName '/Scope_Unreal_X'], ...
    'Position', [960 280 990 310]);
add_block('simulink/Sinks/Scope', [modelName '/Scope_Unreal_Yaw'], ...
    'Position', [960 340 990 370]);

add_line(modelName, 'Teleop_Tick/1', 'Mcl_Map_Pose/1', 'autorouting', 'on');
add_line(modelName, 'Mcl_Map_Pose/1', 'MapPose_To_Unreal/1', 'autorouting', 'on');
add_line(modelName, 'Mcl_Map_Pose/1', 'Scope_Map_Valid/1', 'autorouting', 'on');
add_line(modelName, 'MapPose_To_Unreal/1', 'Unreal_Pose_Gate/1', 'autorouting', 'on');
add_line(modelName, 'MapPose_To_Unreal/1', 'Scope_Unreal_Raw_X/1', 'autorouting', 'on');
add_line(modelName, 'Unreal_Pose_Gate/1', 'Unreal_Pose_Demux/1', 'autorouting', 'on');
add_line(modelName, 'Unreal_Pose_Demux/1', 'Scope_Unreal_X/1', 'autorouting', 'on');
add_line(modelName, 'Unreal_Pose_Demux/4', 'Scope_Unreal_Yaw/1', 'autorouting', 'on');
end

function addUnreal(modelName, unrealProject, spawn, spawnPosStr, cameraPosStr)
add_block("drivingsim3d/Simulation 3D Scene Configuration", ...
    modelName + "/Room_Scene", ...
    "ProjectFormat", "Unreal Editor", ...
    "UEProjPath", unrealProject, ...
    "ScenePath", "/Game/Maps/MyRoom", ...
    "EnableWindow", "on", ...
    "Ts", "0.1", ...
    "Position", [1060 30 1290 165]);

set_param(modelName + "/Room_Scene", ...
    "vehTagList", "{""Scene Origin"", ""RoverTwin""}", ...
    "vehTag", "RoverTwin", ...
    "FreeCameraInitialTranslation", cameraPosStr, ...
    "FreeCameraInitialRotation", "[-15, 0, 0]");

add_block("sim3dlib/Simulation 3D Actor Transform Set", ...
    modelName + "/Set_RoverTwin", ...
    "ActorTag", "RoverTwin", ...
    "NumberOfParts", "1", ...
    "Translation", spawnPosStr, ...
    "Rotation", "[0 0 0]", ...
    "Scale", "[1 1 1]", ...
    "Ts", "0.1", ...
    "Position", [1060 250 1290 345]);

set_param(modelName + "/Set_RoverTwin", "Priority", "-2");
set_param(modelName + "/Room_Scene", "Priority", "0");

add_block("simulink/Sources/Constant", modelName + "/Zero_Pitch", ...
    "Value", "0", ...
    "Position", [725 170 770 200]);
add_block("simulink/Sources/Constant", modelName + "/Zero_Roll", ...
    "Value", "0", ...
    "Position", [725 210 770 240]);
add_block("simulink/Sources/Constant", modelName + "/Unit_Scale", ...
    "Value", "[1 1 1]", ...
    "VectorParams1D", "off", ...
    "Position", [850 315 915 345]);

addVecPack(modelName, "Translation", [760 90 980 150]);
addVecPack(modelName, "Rotation", [805 175 980 250]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/Scale_Spec", ...
    "Dimensions", "[1 3]", ...
    "Position", [955 315 1005 345]);

add_line(modelName, "Unreal_Pose_Demux/1", "Translation_Vec/1", "autorouting", "on");
add_line(modelName, "Unreal_Pose_Demux/2", "Translation_Vec/2", "autorouting", "on");
add_line(modelName, "Unreal_Pose_Demux/3", "Translation_Vec/3", "autorouting", "on");

add_line(modelName, "Zero_Pitch/1", "Rotation_Vec/1", "autorouting", "on");
add_line(modelName, "Zero_Roll/1", "Rotation_Vec/2", "autorouting", "on");
add_line(modelName, "Unreal_Pose_Demux/4", "Rotation_Vec/3", "autorouting", "on");
add_line(modelName, "Unit_Scale/1", "Scale_Spec/1", "autorouting", "on");

add_line(modelName, "Translation_Spec/1", "Set_RoverTwin/1", "autorouting", "on");
add_line(modelName, "Rotation_Spec/1", "Set_RoverTwin/2", "autorouting", "on");
add_line(modelName, "Scale_Spec/1", "Set_RoverTwin/3", "autorouting", "on");

add_block("sim3dlib/Simulation 3D Actor Transform Get", ...
    modelName + "/Get_RoverTwin", ...
    "ActorTag", "RoverTwin", ...
    "NumberOfParts", "1", ...
    "Ts", "-1", ...
    "Position", [1060 400 1290 460]);
add_block("simulink/Sinks/Scope", modelName + "/Scope_Get_X", ...
    "Position", [1330 405 1360 435]);
add_line(modelName, "Get_RoverTwin/1", "Scope_Get_X/1", "autorouting", "on");
end

function addRosPublisher(modelName)
blankBlock = [modelName '/CmdVel_Blank'];
pubBlock = [modelName '/Publish_CmdVel'];

add_block('roslib/ROS 2/Blank Message', blankBlock, ...
    'Position', [390 470 525 520]);
set_param(blankBlock, ...
    'messageClass', 'Message', ...
    'entityType', 'geometry_msgs/Twist', ...
    'SampleTime', '0');
try
    ros.slros2.internal.block.MessageBlockMask.dispatch('entityTypeEdit', blankBlock);
catch
end

add_block('simulink/Signal Routing/Bus Assignment', [modelName '/CmdVel_Assign'], ...
    'AssignedSignals', 'linear.x,angular.z', ...
    'Position', [575 460 705 530]);

add_block('roslib/ROS 2/Publish', pubBlock, ...
    'Position', [760 465 895 525]);
set_param(pubBlock, ...
    'topicSource', 'Specify your own', ...
    'topic', '/cmd_vel', ...
    'messageType', 'geometry_msgs/Twist', ...
    'QOSReliability', 'Reliable', ...
    'QOSDurability', 'Volatile', ...
    'QOSDepth', '10');
try
    ros.slros2.internal.block.PublishBlockMask.dispatch('messageTypeEdit', pubBlock);
catch
end

add_line(modelName, 'CmdVel_Blank/1', 'CmdVel_Assign/1', 'autorouting', 'on');
add_line(modelName, 'CmdVel_Assign/1', 'Publish_CmdVel/1', 'autorouting', 'on');
end

function wireDualOutputs(modelName)
add_line(modelName, "Teleop_Linear/1", "CmdVel_Assign/2", "autorouting", "on");
add_line(modelName, "Teleop_Angular/1", "CmdVel_Assign/3", "autorouting", "on");
end

function addVecPack(modelName, prefix, pos)
vecName = prefix + "_Vec";
packName = "Pack_" + prefix;
specName = prefix + "_Spec";

add_block("simulink/Signal Routing/Vector Concatenate", ...
    modelName + "/" + vecName, ...
    "NumInputs", "3", ...
    "Mode", "Vector", ...
    "ConcatenateDimension", "2", ...
    "Position", [pos(1) pos(2) pos(1)+55 pos(4)]);
add_block("simulink/Math Operations/Reshape", ...
    modelName + "/" + packName, ...
    "OutputDimensions", "[1 3]", ...
    "Position", [pos(1)+75 pos(2)+20 pos(1)+130 pos(2)+50]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/" + specName, ...
    "Dimensions", "[1 3]", ...
    "Position", [pos(1)+150 pos(2)+20 pos(1)+200 pos(2)+50]);

add_line(modelName, vecName + "/1", packName + "/1", "autorouting", "on");
add_line(modelName, packName + "/1", specName + "/1", "autorouting", "on");
end

function addNotes(modelName)
annotationText = ...
    "ROVER DUAL CONTROL — Stage 4" + newline + ...
    "  Teleop -> ROS 2 /cmd_vel -> real rover" + newline + ...
    "  Clock -> MCL on saved map -> unreal_alignment -> pose gate -> Set_RoverTwin" + newline + ...
    "Prereqs: start_agent.sh, maps/unreal_alignment.mat, maps/mcl_lidar_offset.mat, /odom+/scan.";
annotation = Simulink.Annotation(modelName, annotationText);
annotation.Position = [35 20 760 80];
annotation.FontSize = 12;
end
