function sub = robot_ros_subscriber(node, topic, msgType)
%ROBOT_ROS_SUBSCRIBER  QoS matched to Yahboom micro-ROS publishers.

    if strcmp(topic, '/scan')
        sub = ros2subscriber(node, topic, msgType, ...
            'Reliability', 'besteffort', ...
            'Durability', 'volatile', ...
            'Depth', 10);
    else
        sub = ros2subscriber(node, topic, msgType, ...
            'Reliability', 'reliable', ...
            'Durability', 'volatile', ...
            'Depth', 10);
    end
end

