function saveFig = stage2_save_window(slam)
%STAGE2_SAVE_WINDOW  Popup: press 5 or click Save — writes maps/ immediately.

    saveFig = figure('Name', 'Stage 2 — Save map', 'NumberTitle', 'off', ...
        'MenuBar', 'none', 'ToolBar', 'none', ...
        'Position', [120 420 560 240], 'Resize', 'off', ...
        'Color', [0.94 0.94 0.94]);

    uicontrol(saveFig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.05 0.72 0.9 0.22], ...
        'String', 'Click this window, then press 5 to save', ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'BackgroundColor', get(saveFig, 'Color'), 'HorizontalAlignment', 'center');

    statusText = uicontrol(saveFig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.05 0.38 0.9 0.32], ...
        'String', 'Waiting for scans...', ...
        'FontSize', 11, 'ForegroundColor', [0.15 0.15 0.15], ...
        'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left');

    saveBtn = uicontrol(saveFig, 'Style', 'pushbutton', 'Units', 'normalized', ...
        'Position', [0.25 0.08 0.5 0.22], ...
        'String', 'Save map now  (key 5)', ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'Callback', @(~, ~) stage2_save_from_window(saveFig));

    ud = struct( ...
        'slam', slam, ...
        'statusText', statusText, ...
        'saveBtn', saveBtn, ...
        'scanCount', 0, ...
        'saving', false);
    saveFig.UserData = ud;
    saveFig.WindowKeyPressFcn = @onSaveKeyPress;

    stage2_save_window_set_status(saveFig, ...
        'Ready. Drive the robot, then press 5 here or click Save.');
end

function onSaveKeyPress(fig, evt)
    if ~stage2_is_key_five(evt)
        return;
    end
    stage2_save_from_window(fig);
end
