function modelPath = build_rover_control_model()
%BUILD_ROVER_CONTROL_MODEL Create the RoverTwin interactive control model.

matlabFolder = fileparts(mfilename("fullpath"));
unrealProject = rover_unreal_project_alias();
spawn = rover_spawn_pose();
cfg = rover_cmd_vel_config();
spawnPosStr = mat2str(spawn.sim_m, 8);
cameraPosStr = mat2str([spawn.sim_m(1), spawn.sim_m(2), 4], 8);
spawnYawRad = deg2rad(spawn.yaw_deg + cfg.mesh_yaw_offset_deg);
modelName = "RoverTwinControl";
modelPath = fullfile(matlabFolder, modelName + ".slx");

load_system("simulink");
load_system("drivingsim3d");
load_system("sim3dlib");
load_system("sl3dlib");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "0.02", ...
    "StopTime", "inf", ...
    "SimulationMode", "normal", ...
    "InitFcn", "rover_prepare_simulation", ...
    "StopFcn", "rover_stop_simulation");

add_block("drivingsim3d/Simulation 3D Scene Configuration", ...
    modelName + "/Room Scene", ...
    "ProjectFormat", "Unreal Editor", ...
    "UEProjPath", unrealProject, ...
    "ScenePath", "/Game/Maps/MyRoom", ...
    "EnableWindow", "on", ...
    "Ts", "0.02", ...
    "Position", [920 30 1160 170]);

% ── Transform Set: sends Translation/Rotation/Scale to the pre-placed
%    RoverTwin actor every 20 ms.  NO new actor is created — Unreal owns
%    the mesh.  Tag must exactly match the actor's tag in the level.
add_block("sim3dlib/Simulation 3D Actor Transform Set", ...
    modelName + "/Set RoverTwin", ...
    "ActorTag",    "RoverTwin", ...
    "NumberOfParts", "1", ...
    "Translation", spawnPosStr, ...
    "Rotation",    "[0 0 0]", ...
    "Scale",       "[1 1 1]", ...
    "Ts",          "0.02", ...
    "Position",    [920 280 1160 370]);

% ── Transform Get: reads pose from the same RoverTwin actor Transform Set drives.
%    Port 1 → Translation [X Y Z] m, Port 2 → Rotation [pitch roll yaw] rad,
%    Port 3 → (extra, terminated).
add_block("sim3dlib/Simulation 3D Actor Transform Get", ...
    modelName + "/Get RoverTwin", ...
    "ActorTag",    "RoverTwin", ...
    "NumberOfParts", "1", ...
    "Ts",          "-1", ...
    "Position",    [920 390 1160 450]);

% MathWorks: Transform Set must run before Scene Configuration (lower priority #).
set_param(modelName + "/Set RoverTwin", "Priority", "-2");
set_param(modelName + "/Room Scene",    "Priority", "0");

% Terminate unused 3rd output of Transform Get.
add_block("simulink/Sinks/Terminator", modelName + "/Get Term", ...
    "Position", [1200 430 1225 460]);
add_line(modelName, "Get RoverTwin/3", "Get Term/1");

% ── Lidar: GPU raycast sensor mounted on the commanded RoverTwin actor.
%    The top radar/lidar-looking mesh is visual only; this block is the
%    actual Simulation 3D sensor that streams XYZ points back to MATLAB.
add_block("sl3dlib/Simulation 3D/Sensors/Simulation 3D Lidar", ...
    modelName + "/RoverTwin Lidar", ...
    "sensorTag",  "RoverTwinLidar", ...
    "sensorName", "RoverTwinLidar", ...
    "vehTagList", "{""Scene Origin"", ""RoverTwin""}", ...
    "vehTag", "RoverTwin", ...
    "mountLoc", "Origin", ...
    "offsetFlag", "on", ...
    "tmountOffset", "[0, 0, 0]", ...
    "rmountOffset", "[0, 0, 0]", ...
    "DetectionRange", "8", ...
    "HorizontalFOV", "360", ...
    "HorizontalResolution", "1", ...
    "VerticalFOV", "1", ...
    "VerticalResolution", "1", ...
    "SampleTime", "0.1", ...
    "Position", [1260 565 1480 645]);

add_block("simulink/User-Defined Functions/MATLAB System", ...
    modelName + "/Live Lidar Plot", ...
    "System", "roverLidarLivePlot", ...
    "SimulateUsing", "Interpreted execution", ...
    "Position", [1540 570 1690 640]);
add_line(modelName, "RoverTwin Lidar/1", "Live Lidar Plot/1", "autorouting", "on");

add_block("simulink/Sources/Clock", modelName + "/Simulation Time", ...
    "Position", [1455 655 1490 685]);
add_line(modelName, "Simulation Time/1", "Live Lidar Plot/2", "autorouting", "on");

% Force the sensor actor to follow RoverTwin.  The lidar block's vehTag mount
% can refresh data while keeping a stale world position for actors moved by
% Simulation 3D Actor Transform Set, so we move the generated sensor actor too.
add_block("sim3dlib/Simulation 3D Actor Transform Set", ...
    modelName + "/Set RoverTwinLidar", ...
    "ActorTag",    "RoverTwinLidar", ...
    "NumberOfParts", "1", ...
    "Translation", spawnPosStr, ...
    "Rotation",    "[0 0 0]", ...
    "Scale",       "[1 1 1]", ...
    "Ts",          "0.02", ...
    "Position",    [1260 675 1480 765]);
set_param(modelName + "/Set RoverTwinLidar", "Priority", "-1");

% Feedback demux — keyboard UI reads Actual X/Y/Yaw Deg Gain blocks.
% Port 1 of Get RoverTwin = Translation [X Y Z] m (row vector)
% Port 2 of Get RoverTwin = Rotation [Pitch Roll Yaw] rad (row vector)
% (MathWorks Transform Set/Get reference: column order is pitch, roll, yaw;
%  yaw is index 3 — NOT index 2.)
add_block("simulink/Signal Routing/Demux", modelName + "/Actual Position Demux", ...
    "Outputs", "3", "Position", [1200 325 1205 365]);
add_block("simulink/Signal Routing/Demux", modelName + "/Actual Yaw Demux", ...
    "Outputs", "3", "Position", [1200 375 1205 415]);
add_line(modelName, "Get RoverTwin/1", "Actual Position Demux/1", "autorouting", "on");
add_line(modelName, "Get RoverTwin/2", "Actual Yaw Demux/1",      "autorouting", "on");

add_block("simulink/Math Operations/Gain", modelName + "/Actual X", ...
    "Gain", "1", "Position", [1225 320 1265 340]);
add_block("simulink/Math Operations/Gain", modelName + "/Actual Y", ...
    "Gain", "1", "Position", [1225 350 1265 370]);
add_block("simulink/Math Operations/Gain", modelName + "/Actual Z", ...
    "Gain", "1", "Position", [1225 380 1265 400]);
add_block("simulink/Math Operations/Gain", modelName + "/Actual Roll", ...
    "Gain", "1", "Position", [1225 420 1265 440]);
add_block("simulink/Math Operations/Gain", modelName + "/Actual Pitch", ...
    "Gain", "1", "Position", [1225 450 1265 470]);
add_block("simulink/Math Operations/Gain", modelName + "/Actual Yaw", ...
    "Gain", "1", "Position", [1225 480 1265 500]);

add_line(modelName, "Actual Position Demux/1", "Actual X/1");
add_line(modelName, "Actual Position Demux/2", "Actual Y/1");
add_line(modelName, "Actual Position Demux/3", "Actual Z/1");
add_line(modelName, "Actual Yaw Demux/1", "Actual Pitch/1");
add_line(modelName, "Actual Yaw Demux/2", "Actual Roll/1");
add_line(modelName, "Actual Yaw Demux/3", "Actual Yaw/1");

% Free camera starts directly above the rover's spawn position.
% vehTag = "RoverTwin" would follow the rover; "Scene Origin" keeps camera
% fixed — change to "RoverTwin" if you want the camera to track the rover.
set_param(modelName + "/Room Scene", ...
    "vehTagList", "{""Scene Origin"", ""RoverTwin""}", ...
    "vehTag", "Scene Origin", ...
    "FreeCameraInitialTranslation", cameraPosStr, ...
    "FreeCameraInitialRotation", "[-90, 0, 0]");

addCommandValue(modelName, "Forward Value", [240 55 330 85]);
addCommandValue(modelName, "Left Value", [240 145 330 175]);
addCommandValue(modelName, "Stop Value", [350 145 440 175]);
addCommandValue(modelName, "Right Value", [480 145 570 175]);
addCommandValue(modelName, "Reverse Value", [350 235 440 265]);

add_block("simulink/Math Operations/Sum", modelName + "/Forward Minus Reverse", ...
    "Inputs", "+-", "Position", [380 50 410 105]);
add_line(modelName, "Forward Value/1", "Forward Minus Reverse/1");
add_line(modelName, "Reverse Value/1", "Forward Minus Reverse/2");

add_block("simulink/Math Operations/Sum", modelName + "/Left Minus Right", ...
    "Inputs", "+-", "Position", [610 145 640 200]);
add_line(modelName, "Left Value/1", "Left Minus Right/1");
add_line(modelName, "Right Value/1", "Left Minus Right/2");

add_block("simulink/Math Operations/Product", modelName + "/Stop Gate", ...
    "Inputs", "**", "Position", [470 55 505 105]);
add_block("simulink/Math Operations/Gain", modelName + "/Run Enable", ...
    "Gain", "-1", "Position", [470 235 520 265]);
add_block("simulink/Math Operations/Bias", modelName + "/One Minus Stop", ...
    "Bias", "1", "Position", [550 235 610 265]);
add_line(modelName, "Stop Value/1", "Run Enable/1");
add_line(modelName, "Run Enable/1", "One Minus Stop/1");
add_line(modelName, "Forward Minus Reverse/1", "Stop Gate/1");
add_line(modelName, "One Minus Stop/1", "Stop Gate/2");

% /cmd_vel semantics: linear.x and angular.z (same as physical micro-ROS rover)
add_block("simulink/Math Operations/Gain", modelName + "/CmdVel Linear", ...
    "Gain", string(cfg.linear_speed_mps), "Position", [540 60 600 100]);
add_block("simulink/Math Operations/Gain", modelName + "/CmdVel Angular", ...
    "Gain", string(cfg.angular_speed_rps), "Position", [680 150 740 190]);
add_line(modelName, "Stop Gate/1", "CmdVel Linear/1");
add_line(modelName, "Left Minus Right/1", "CmdVel Angular/1");

add_block("simulink/Discrete/Discrete-Time Integrator", modelName + "/Yaw", ...
    "InitialCondition", string(spawnYawRad), "SampleTime", string(cfg.sample_time_s), ...
    "Position", [775 150 805 180]);
add_line(modelName, "CmdVel Angular/1", "Yaw/1");

add_block("simulink/Math Operations/Trigonometric Function", ...
    modelName + "/Cos Yaw", "Operator", "cos", ...
    "Position", [650 45 700 75]);
add_block("simulink/Math Operations/Trigonometric Function", ...
    modelName + "/Sin Yaw", "Operator", "sin", ...
    "Position", [650 95 700 125]);
add_line(modelName, "Yaw/1", "Cos Yaw/1", "autorouting", "on");
add_line(modelName, "Yaw/1", "Sin Yaw/1", "autorouting", "on");

add_block("simulink/Math Operations/Product", modelName + "/X Velocity", ...
    "Position", [740 45 775 80]);
add_block("simulink/Math Operations/Product", modelName + "/Y Velocity", ...
    "Position", [740 95 775 130]);
add_line(modelName, "CmdVel Linear/1", "X Velocity/1");
add_line(modelName, "Cos Yaw/1", "X Velocity/2");
add_line(modelName, "CmdVel Linear/1", "Y Velocity/1", "autorouting", "on");
add_line(modelName, "Sin Yaw/1", "Y Velocity/2");

% Simple integrators — commanded pose; Transform Set teleports the visible rover.
add_block("simulink/Discrete/Discrete-Time Integrator", ...
    modelName + "/X Position", ...
    "InitialCondition", string(spawn.sim_m(1)), "SampleTime", string(cfg.sample_time_s), ...
    "Position", [810 45 840 75]);
% Y integrator runs in the ROS right-handed frame (y points left).
% The LH Unreal spawn Y is +sim_m(2); the RH equivalent is its negative.
add_block("simulink/Discrete/Discrete-Time Integrator", ...
    modelName + "/Y Position", ...
    "InitialCondition", string(-spawn.sim_m(2)), "SampleTime", string(cfg.sample_time_s), ...
    "Position", [810 95 840 125]);
add_line(modelName, "X Velocity/1", "X Position/1");
add_line(modelName, "Y Velocity/1", "Y Position/1");

add_block("simulink/Sources/Constant", modelName + "/Z Position", ...
    "Value", string(spawn.sim_m(3)), "Position", [810 255 850 285]);

% Transform Set requires 1-by-3 matrices (MathWorks ActorTransformWriter).
add_block("simulink/Signal Routing/Vector Concatenate", ...
    modelName + "/Translation Vec", ...
    "NumInputs", "3", "Mode", "Vector", ...
    "ConcatenateDimension", "2", "Position", [870 65 920 145]);
add_block("simulink/Math Operations/Reshape", modelName + "/Pack Translation", ...
    "OutputDimensions", "[1 3]", "Position", [935 85 985 115]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/Translation Spec", ...
    "Dimensions", "[1 3]", "Position", [1000 85 1045 115]);
% RH→LH conversion (MathWorks (x,-y,z,-yaw) mapping): flip Y for the LH
% Unreal world. X and Z are identical in both frames.
add_block("simulink/Math Operations/Gain", modelName + "/Set Y Flip", ...
    "Gain", string(cfg.y_translation_sign), "Position", [895 150 925 170]);
add_line(modelName, "X Position/1", "Translation Vec/1");
add_line(modelName, "Y Position/1", "Set Y Flip/1", "autorouting", "on");
add_line(modelName, "Set Y Flip/1", "Translation Vec/2", "autorouting", "on");
add_line(modelName, "Z Position/1", "Translation Vec/3", "autorouting", "on");
add_line(modelName, "Translation Vec/1", "Pack Translation/1");
add_line(modelName, "Pack Translation/1", "Translation Spec/1");
add_block("simulink/Sources/Constant", modelName + "/Lidar Z Offset", ...
    "Value", "0.079", "Position", [1015 130 1065 160]);
add_block("simulink/Math Operations/Sum", modelName + "/Lidar Z Position", ...
    "Inputs", "++", "Position", [1085 230 1115 275]);
add_block("simulink/Signal Routing/Vector Concatenate", ...
    modelName + "/Lidar Translation Vec", ...
    "NumInputs", "3", "Mode", "Vector", ...
    "ConcatenateDimension", "2", "Position", [1135 600 1185 680]);
add_block("simulink/Math Operations/Reshape", modelName + "/Pack Lidar Translation", ...
    "OutputDimensions", "[1 3]", "Position", [1200 620 1250 650]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/Lidar Translation Spec", ...
    "Dimensions", "[1 3]", "Position", [1265 620 1310 650]);
add_line(modelName, "X Position/1", "Lidar Translation Vec/1", "autorouting", "on");
add_line(modelName, "Set Y Flip/1", "Lidar Translation Vec/2", "autorouting", "on");
add_line(modelName, "Z Position/1", "Lidar Z Position/1", "autorouting", "on");
add_line(modelName, "Lidar Z Offset/1", "Lidar Z Position/2", "autorouting", "on");
add_line(modelName, "Lidar Z Position/1", "Lidar Translation Vec/3", "autorouting", "on");
add_line(modelName, "Lidar Translation Vec/1", "Pack Lidar Translation/1");
add_line(modelName, "Pack Lidar Translation/1", "Lidar Translation Spec/1");

% Rotation: [pitch roll yaw] in radians (MathWorks Transform Set reference —
% yaw is index 3, the Z-axis slot; index 2 is roll). Yaw is negated here
% (RH→LH, the -yaw half of the (x,-y,z,-yaw) mapping) so the rendered heading
% matches the flipped-Y translation path. The cos/sin velocity terms still use
% the un-flipped ROS yaw above.
add_block("simulink/Sources/Constant", modelName + "/Zero Pitch", ...
    "Value", "0", "Position", [810 175 850 205]);
add_block("simulink/Sources/Constant", modelName + "/Zero Roll", ...
    "Value", "0", "Position", [810 215 850 245]);
add_block("simulink/Math Operations/Gain", modelName + "/Set Yaw Flip", ...
    "Gain", string(cfg.mesh_yaw_sign), "Position", [820 145 850 165]);
add_block("simulink/Signal Routing/Vector Concatenate", ...
    modelName + "/Rotation Vec", ...
    "NumInputs", "3", "Mode", "Vector", ...
    "ConcatenateDimension", "2", "Position", [870 175 920 255]);
add_block("simulink/Math Operations/Reshape", modelName + "/Pack Rotation", ...
    "OutputDimensions", "[1 3]", "Position", [935 195 985 225]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/Rotation Spec", ...
    "Dimensions", "[1 3]", "Position", [1000 195 1045 225]);
add_line(modelName, "Yaw/1",         "Set Yaw Flip/1", "autorouting", "on");
add_line(modelName, "Zero Pitch/1", "Rotation Vec/1");
add_line(modelName, "Zero Roll/1",  "Rotation Vec/2");
add_line(modelName, "Set Yaw Flip/1", "Rotation Vec/3", "autorouting", "on");
add_line(modelName, "Rotation Vec/1", "Pack Rotation/1");
add_line(modelName, "Pack Rotation/1", "Rotation Spec/1");
add_line(modelName, "X Position/1", "Live Lidar Plot/3", "autorouting", "on");
add_line(modelName, "Set Y Flip/1", "Live Lidar Plot/4", "autorouting", "on");
add_line(modelName, "Set Yaw Flip/1", "Live Lidar Plot/5", "autorouting", "on");

add_block("simulink/Sources/Constant", modelName + "/Unit Scale", ...
    "Value", "[1 1 1]", "VectorParams1D", "off", ...
    "Position", [870 305 930 335]);
add_block("simulink/Signal Attributes/Signal Specification", ...
    modelName + "/Scale Spec", ...
    "Dimensions", "[1 3]", "Position", [960 305 1005 335]);
add_line(modelName, "Unit Scale/1", "Scale Spec/1");

add_line(modelName, "Translation Spec/1", "Set RoverTwin/1");
add_line(modelName, "Rotation Spec/1",    "Set RoverTwin/2");
add_line(modelName, "Scale Spec/1",       "Set RoverTwin/3");
add_line(modelName, "Lidar Translation Spec/1", "Set RoverTwinLidar/1");
add_line(modelName, "Rotation Spec/1",          "Set RoverTwinLidar/2");
add_line(modelName, "Scale Spec/1",             "Set RoverTwinLidar/3");

annotationText = sprintf([ ...
    'ROVERTWIN CONTROL — /cmd_vel drive model + Transform Set/Get\n', ...
    '1. In MATLAB run:  open_rover_control\n', ...
    '2. Click Run — wait for Unreal to open, then Play starts automatically.\n', ...
    '3. Click the RoverTwin Keyboard Control window.\n', ...
    '4. W/S = linear.x, A/D = angular.z, Q/E = slower/faster, SPACE = stop.\n', ...
    '5. Same unicycle model as firmware odom_update() in micro-ROS.\n', ...
    '6. Unreal mesh is driven by integrated pose — not wheel physics.\n', ...
    '7. Level repair: scripts/run_disable_collision.sh (one RoverTwin only).']);
annotation = Simulink.Annotation(modelName, annotationText);
annotation.Position = [25 320 520 405];
annotation.FontSize = 13;

save_system(modelName, modelPath);
set_param(modelName, "ZoomFactor", "FitSystem");
fprintf("Created %s\n", modelPath);
end

function addCommandValue(modelName, valueName, valuePosition)
add_block("simulink/Sources/Constant", modelName + "/" + valueName, ...
    "Value", "0", "OutDataTypeStr", "double", ...
    "Position", valuePosition);
end
