#!/usr/bin/env bash
# Fix known stale path artifacts after moving the project tree.
set -eo pipefail
# shellcheck source=lib/common.sh
source "$(dirname "$0")/lib/common.sh"

ROOT="$REPLICA_ROOT"
PROJECT="$ROOT"
IDF_JSON="$ROOT/tooling/espressif/idf-env.json"

echo "=== fix_stale_paths ==="

# 1. idf-env.json — point at current bundled IDF only
if [ -f "$IDF_JSON" ]; then
  echo "Updating idf-env.json..."
  cat > "$IDF_JSON" <<EOF
{
    "idfInstalled": {
        "$PROJECT/esp/esp-idf": {
            "version": "5.1",
            "path": "$PROJECT/esp/esp-idf",
            "features": ["core"],
            "targets": ["esp32", "esp32s2", "esp32s3", "esp32c2", "esp32c3", "esp32c6", "esp32h2"]
        }
    }
}
EOF
fi

# 2. Generated toolchain files (regenerated by libmicroros.mk on next build)
for f in \
  "$ROOT/esp/Samples/extra_components/micro_ros_espidf_component/esp32_toolchain.cmake" \
  "$ROOT/esp/Samples/custom_components/micro_ros_espidf_component/esp32_toolchain.cmake"; do
  if [ -f "$f" ] && grep -qE '/home/yahboom|replica-done/replica/' "$f" 2>/dev/null; then
    echo "Removing stale $f"
    rm -f "$f"
  fi
done

# 3. Optional legacy WSL build copy
LINUX="$HOME/yahboom_esp_build"
if [ -d "$LINUX" ]; then
  rm -f "$LINUX/Samples/extra_components/micro_ros_espidf_component/esp32_toolchain.cmake" 2>/dev/null || true
fi

# 4. IDF Python venv — broken pip3 shebangs after folder rename
VENV_PY="$ROOT/tooling/espressif/python_env/idf5.1_py3.10_env/bin/python"
if [ -x "$VENV_PY" ]; then
  if head -1 "$ROOT/tooling/espressif/python_env/idf5.1_py3.10_env/bin/pip3" 2>/dev/null \
    | grep -q 'replica-done/replica/'; then
    echo "Broken IDF venv shebangs detected — recreating python_env..."
    "$ROOT/scripts/fix_idf_python.sh"
  else
    echo "IDF Python venv shebangs OK (or pip3 missing)"
  fi
else
  echo "IDF Python venv missing — run: ./scripts/fix_idf_python.sh"
fi

echo ""
echo "Done. Run ./scripts/audit_stale_paths.sh to verify."
